name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['*.md', LICENSE, .gitignore, .husky/**]
  pull_request:
    branches: [main]
    paths-ignore: ['*.md', LICENSE, .gitignore, .husky/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  lint:
    name: Format, lint, typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install
        id: install
        run: pnpm install

      - name: Format
        run: pnpm run format

      - name: Lint
        if: always() && steps.install.outcome == 'success'
        run: pnpm run lint

      - name: Typecheck
        if: always() && steps.install.outcome == 'success'
        run: pnpm run typecheck

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
          retention-days: 7
